import './globals.css'

import type {Metadata} from 'next'
import {League_Spartan} from 'next/font/google'
import React from 'react'

import {ThemeProvider} from '@/app/theme-provider'

const leagueSpartan = League_Spartan({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
                                     children
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body className={leagueSpartan.className}>
    <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
      {children}
    </ThemeProvider>
    </body>
    </html>
  )
}
